# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:

a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)

print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.0250179  0.23191222 0.05107696 ... 0.36572758 0.84642972 0.6053635 ]
 [0.91290407 0.25807223 0.95989805 ... 0.24788218 0.57316742 0.71244221]
 [0.16829931 0.99239197 0.53310002 ... 0.04494354 0.79443017 0.605047  ]
 ...
 [0.20974874 0.70594018 0.43725837 ... 0.96051432 0.3109354  0.99474009]
 [0.68211082 0.08380005 0.14453147 ... 0.39985122 0.75492459 0.28914196]
 [0.74446677 0.68956869 0.43142278 ... 0.09335798 0.05143533 0.07581835]]
[[0.29394531 0.27121171 0.2651928  ... 0.45734854 0.85783101 0.93113581]
 [0.62222955 0.06174786 0.5768922  ... 0.86994934 0.24896037 0.17452578]
 [0.07957103 0.85374742 0.7468708  ... 0.93485868 0.76711171 0.8663198 ]
 ...
 [0.97279744 0.68106198 0.44263511 ... 0.38219346 0.91976934 0.86997776]
 [0.18582837 0.18467312 0.05590404 ... 0.75059419 0.02500144 0.99608694]
 [0.52698662 0.06927334 0.63272069 ... 0.57665898 0.52231259 0.90886483]]


Без использования numpy

In [ ]:
def mult(a, b):
    assert a.shape[1] == b.shape[0], "Matrices are not compatible for multiplication"

    m = a.shape[0]
    n = b.shape[1]
    p = a.shape[1]

    result = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            for k in range(p):
                result[i][j] += a[i][k] * b[k][j]

    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    assert a.shape[1] == b.shape[0], "Matrices are not compatible for multiplication"
    result = np.dot(a, b)

    return result

In [ ]:
%%time
M1 = mult(a, b)

CPU times: user 926 ms, sys: 1.31 ms, total: 927 ms
Wall time: 934 ms


In [ ]:
%%time
M2 = np_mult(a, b)

CPU times: user 1.71 ms, sys: 2.89 ms, total: 4.6 ms
Wall time: 4.43 ms


In [ ]:

np.abs(np.array(M1) - M2).sum()

1.5059953284435323e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.61321576 0.1796096  0.38153969] [0.34094926 0.64998456 0.47489815]


In [ ]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [ ]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
np.abs(product_1 - product_2).sum()

CPU times: user 21 µs, sys: 3 µs, total: 24 µs
Wall time: 29.1 µs
CPU times: user 101 µs, sys: 16 µs, total: 117 µs
Wall time: 2.65 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** NumPy позволяет выполнять операции над целыми массивами данных сразу, без явного использования циклов. Это позволяет библиотеке использовать оптимизированные бинарные функции, написанные на C или Fortran, что обеспечивает высокую производительность.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
def np_diag_2k(a):
    diag = np.diag(a)
    even_diag = diag[diag % 2 == 0]
    if len(even_diag) == 0:
        return 0
    else:
        return np.sum(even_diag)

In [ ]:

a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 8, 1, 7, 7],
       [8, 1, 4, 5, 5],
       [6, 3, 9, 3, 5],
       [5, 6, 3, 6, 9],
       [3, 9, 2, 7, 4]])

In [ ]:
%%time
np_diag_2k(a)

CPU times: user 131 µs, sys: 0 ns, total: 131 µs
Wall time: 135 µs


10

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
def np_sec_av(*A):
    X = np.array(A)
    cumsum = np.cumsum(X, axis=1)
    row_indices = np.arange(1, X.shape[1] + 1)
    result = cumsum / row_indices[:, np.newaxis]
    return result

In [ ]:
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.0277471  0.74464714 0.58403231 0.7591272  0.23633027 0.43048409
 0.56471744 0.28059111 0.06590542 0.63337091 0.2614657  0.67439523
 0.55090391 0.53022281 0.65813588 0.58481218 0.59970942 0.98263334
 0.09955184 0.28284643 0.93315212 0.27132636 0.5339299  0.56563658
 0.23203068 0.52654191 0.41836834 0.73353125 0.96283657 0.98502658
 0.49425537 0.02385625 0.17808165 0.6546974  0.83849248 0.01165507
 0.05805259 0.04530307 0.18496779 0.55667307 0.04271428 0.89532958
 0.80915133 0.05150851 0.76293574 0.36015567 0.10623199 0.36486652
 0.40272687 0.17496035 0.69132102 0.55959863 0.27669079 0.49869751
 0.79746588 0.56423504 0.33854723 0.90251078 0.8913049  0.86157093
 0.42224274 0.937464   0.60334584 0.92718069 0.07275878 0.24435685
 0.66442035 0.20508451 0.93031734 0.77224185 0.6289301  0.39560913
 0.31095035 0.57343887 0.04174002 0.59416174 0.25203115 0.99679042
 0.72919765 0.0207454  0.57982887 0.17613312 0.87102877 0.67894958
 0.75550003 0.45699748 0.58846167 0.52577642 0.19956404 0.6202

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
def np_encode(a):
    result = []
    count = 1
    for i in range(1, len(a)):
        if a[i] == a[i-1]:
            count += 1
        else:
            result.append(a[i-1])
            result.append(count)
            count = 1
    result.append(a[-1])
    result.append(count)

    return np.array(result[0::2]), np.array(result[1::2])

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(x,num)

CPU times: user 36 µs, sys: 5 µs, total: 41 µs
Wall time: 44.8 µs
[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    X_copy = np.copy(X)
    X_copy[1::2] = a
    X_copy[::2] = np.power(X_copy[::2], 3)
    result = np.concatenate((X, X_copy[::-1]))
    return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(S2)

CPU times: user 1.06 ms, sys: 5 µs, total: 1.06 ms
Wall time: 3.28 ms
[  1   3   5   7   9 729   5 125   5   1]
